-- 1. CREATE TABLE

CREATE TABLE STUDENT (
    STUDENT_ID NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(50),
    DEPARTMENT_ID NUMBER
);


-- 2. INSERT SAMPLE RECORDS

INSERT INTO STUDENT VALUES (101, 'Arun', 10);
INSERT INTO STUDENT VALUES (102, 'Priya', 20);
INSERT INTO STUDENT VALUES (103, 'Kumar', 10);
INSERT INTO STUDENT VALUES (104, 'Divya', 30);
INSERT INTO STUDENT VALUES (105, 'Ravi', 20);

COMMIT;


-- 3. CREATE CURSOR AND DISPLAY RECORDS

DECLARE

    CURSOR STUDENT_CURSOR IS
        SELECT STUDENT_ID, STUDENT_NAME, DEPARTMENT_ID
        FROM STUDENT;

    V_STUDENT_ID    STUDENT.STUDENT_ID%TYPE;
    V_STUDENT_NAME  STUDENT.STUDENT_NAME%TYPE;
    V_DEPARTMENT_ID STUDENT.DEPARTMENT_ID%TYPE;

BEGIN

    OPEN STUDENT_CURSOR;

    LOOP

        FETCH STUDENT_CURSOR
        INTO V_STUDENT_ID, V_STUDENT_NAME, V_DEPARTMENT_ID;

        EXIT WHEN STUDENT_CURSOR%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'Student ID: ' || V_STUDENT_ID ||
            ', Student Name: ' || V_STUDENT_NAME ||
            ', Department ID: ' || V_DEPARTMENT_ID
        );

    END LOOP;

    CLOSE STUDENT_CURSOR;

END;
/

